const icons = require('iconoir-react');
const keys = Object.keys(icons);
const bookRelated = keys.filter(k => /book|cart|shop|note|star|spark|check|list|food|recipe/i.test(k));
console.log('book/cart/shop/food:', bookRelated.join(', '));
const communityRelated = keys.filter(k => /community|group|people|user|family|share/i.test(k));
console.log('community/people:', communityRelated.join(', '));
const calRelated = keys.filter(k => /calendar|schedule|plan/i.test(k));
console.log('calendar:', calRelated.join(', '));
const sparkRelated = keys.filter(k => /spark|magic|ai|brain|wand|bolt|flash|auto/i.test(k));
console.log('spark/ai:', sparkRelated.join(', '));
const importRelated = keys.filter(k => /import|link|url|arrow|download|upload/i.test(k));
console.log('import/link:', importRelated.join(', '));
