import { 
  Home, 
  Heart, 
  Star, 
  Cloud, 
  Flash, 
  FireFlame, 
  Compass, 
  Map, 
  Camera, 
  MusicDoubleNote, 
  Gamepad, 
  CoffeeCup, 
  PizzaSlice, 
  Bookmark, 
  Notes, 
  Shop, 
  Cart, 
  Calendar,
  User,
  Shield,
  SunLight,
  HalfMoon,
  LightBulb,
  Key,
  Lock,
  Airplane,
  Bus,
  Car,
  Bicycle,
  Fish,
  Tree,
  Flower,
  Leaf,
  SnowFlake,
  Umbrella,
  Glasses,
  Hat,
  Apple,
  Book,
  Calculator,
  StatsReport,
  Mail,
  Folder,
  Globe,
  Trophy,
  Rocket,
  Planet,
  Eye,
  Wifi,
  BatteryFull
} from 'iconoir-react';

export const SHARED_ICON_OPTIONS = [
  { id: '1', name: 'Home', icon: Home },
  { id: '2', name: 'Heart', icon: Heart },
  { id: '3', name: 'Star', icon: Star },
  { id: '4', name: 'Cloud', icon: Cloud },
  { id: '5', name: 'Flash', icon: Flash },
  { id: '6', name: 'FireFlame', icon: FireFlame },
  { id: '7', name: 'Compass', icon: Compass },
  { id: '8', name: 'Map', icon: Map },
  { id: '9', name: 'Camera', icon: Camera },
  { id: '10', name: 'Music', icon: MusicDoubleNote },
  { id: '11', name: 'Gamepad', icon: Gamepad },
  { id: '12', name: 'Coffee', icon: CoffeeCup },
  { id: '13', name: 'Pizza', icon: PizzaSlice },
  { id: '14', name: 'Bookmark', icon: Bookmark },
  { id: '15', name: 'Notes', icon: Notes },
  { id: '16', name: 'Shop', icon: Shop },
  { id: '17', name: 'Cart', icon: Cart },
  { id: '18', name: 'Calendar', icon: Calendar },
  { id: '19', name: 'User', icon: User },
  { id: '20', name: 'Shield', icon: Shield },
  { id: '21', name: 'Sun', icon: SunLight },
  { id: '22', name: 'Moon', icon: HalfMoon },
  { id: '23', name: 'Idea', icon: LightBulb },
  { id: '24', name: 'Key', icon: Key },
  { id: '25', name: 'Lock', icon: Lock },
  { id: '26', name: 'Plane', icon: Airplane },
  { id: '27', name: 'Bus', icon: Bus },
  { id: '28', name: 'Car', icon: Car },
  { id: '29', name: 'Bike', icon: Bicycle },
  { id: '30', name: 'Fish', icon: Fish },
  { id: '31', name: 'Tree', icon: Tree },
  { id: '32', name: 'Flower', icon: Flower },
  { id: '33', name: 'Leaf', icon: Leaf },
  { id: '34', name: 'Snow', icon: SnowFlake },
  { id: '35', name: 'Umbrella', icon: Umbrella },
  { id: '36', name: 'Glasses', icon: Glasses },
  { id: '37', name: 'Hat', icon: Hat },
  { id: '38', name: 'Apple', icon: Apple },
  { id: '39', name: 'Book', icon: Book },
  { id: '40', name: 'Calculator', icon: Calculator },
  { id: '41', name: 'Chart', icon: StatsReport },
  { id: '42', name: 'Mail', icon: Mail },
  { id: '43', name: 'Folder', icon: Folder },
  { id: '44', name: 'Globe', icon: Globe },
  { id: '45', name: 'Trophy', icon: Trophy },
  { id: '46', name: 'Rocket', icon: Rocket },
  { id: '47', name: 'Planet', icon: Planet },
  { id: '48', name: 'Eye', icon: Eye },
  { id: '49', name: 'Wifi', icon: Wifi },
  { id: '50', name: 'Battery', icon: BatteryFull }
];
