import { FaHome, FaHeart, FaStar, FaCloud, FaBolt, FaFire, FaCompass, FaMap, FaCamera, FaMusic, FaGamepad, FaCoffee, FaPizzaSlice, FaBookmark, FaStickyNote, FaStore, FaShoppingCart, FaCalendarAlt, FaUser, FaShieldAlt, FaSun, FaMoon, FaLightbulb, FaKey, FaLock, FaPlane, FaBus, FaCar, FaBicycle, FaFish, FaTree, FaLeaf, FaSnowflake, FaUmbrella, FaGlasses, FaAppleAlt, FaBook, FaCalculator, FaChartBar, FaEnvelope, FaFolder, FaGlobe, FaTrophy, FaRocket, FaEye, FaWifi, FaBatteryFull, FaBreadSlice, FaIceCream, FaUtensils, FaEgg, FaCookieBite, FaDrumstickBite, FaSeedling, FaCarrot, FaCandyCane, FaGraduationCap } from 'react-icons/fa';
import { MdKitchen } from 'react-icons/md';
import { IoPlanet, IoFlower } from 'react-icons/io5';
import { PizzaSlice, CoffeeCup, BreadSlice, IceCream, Fridge as FridgeOutline, Cutlery as CutleryOutline, Egg as EggOutline, Cookie as CookieOutline, Bbq as BbqOutline, Chocolate as ChocolateOutline, OrganicFood, Vegan as VeganOutline } from 'iconoir-react';

export const SHARED_ICON_OPTIONS = [
  { id: '1', name: 'Home', icon: FaHome },
  { id: '2', name: 'Heart', icon: FaHeart },
  { id: '3', name: 'Star', icon: FaStar },
  { id: '4', name: 'Cloud', icon: FaCloud },
  { id: '5', name: 'Flash', icon: FaBolt },
  { id: '6', name: 'FireFlame', icon: FaFire },
  { id: '7', name: 'Compass', icon: FaCompass },
  { id: '8', name: 'Map', icon: FaMap },
  { id: '9', name: 'Camera', icon: FaCamera },
  { id: '10', name: 'Music', icon: FaMusic },
  { id: '11', name: 'Gamepad', icon: FaGamepad },
  { id: '12', name: 'Coffee', icon: FaCoffee },
  { id: '13', name: 'Pizza', icon: FaPizzaSlice },
  { id: '14', name: 'Bookmark', icon: FaBookmark },
  { id: '15', name: 'Notes', icon: FaStickyNote },
  { id: '16', name: 'Shop', icon: FaStore },
  { id: '17', name: 'Cart', icon: FaShoppingCart },
  { id: '18', name: 'Calendar', icon: FaCalendarAlt },
  { id: '19', name: 'User', icon: FaUser },
  { id: '20', name: 'Shield', icon: FaShieldAlt },
  { id: '21', name: 'Sun', icon: FaSun },
  { id: '22', name: 'Moon', icon: FaMoon },
  { id: '23', name: 'Idea', icon: FaLightbulb },
  { id: '24', name: 'Key', icon: FaKey },
  { id: '25', name: 'Lock', icon: FaLock },
  { id: '26', name: 'Plane', icon: FaPlane },
  { id: '27', name: 'Bus', icon: FaBus },
  { id: '28', name: 'Car', icon: FaCar },
  { id: '29', name: 'Bike', icon: FaBicycle },
  { id: '30', name: 'Fish', icon: FaFish },
  { id: '31', name: 'Tree', icon: FaTree },
  { id: '32', name: 'Flower', icon: IoFlower },
  { id: '33', name: 'Leaf', icon: FaLeaf },
  { id: '34', name: 'Snow', icon: FaSnowflake },
  { id: '35', name: 'Umbrella', icon: FaUmbrella },
  { id: '36', name: 'Glasses', icon: FaGlasses },
  { id: '37', name: 'Hat', icon: FaGraduationCap },
  { id: '38', name: 'Apple', icon: FaAppleAlt },
  { id: '39', name: 'Book', icon: FaBook },
  { id: '40', name: 'Calculator', icon: FaCalculator },
  { id: '41', name: 'Chart', icon: FaChartBar },
  { id: '42', name: 'Mail', icon: FaEnvelope },
  { id: '43', name: 'Folder', icon: FaFolder },
  { id: '44', name: 'Globe', icon: FaGlobe },
  { id: '45', name: 'Trophy', icon: FaTrophy },
  { id: '46', name: 'Rocket', icon: FaRocket },
  { id: '47', name: 'Planet', icon: IoPlanet },
  { id: '48', name: 'Eye', icon: FaEye },
  { id: '49', name: 'Wifi', icon: FaWifi },
  { id: '50', name: 'Battery', icon: FaBatteryFull },
  { id: '51', name: 'Bread', icon: FaBreadSlice },
  { id: '52', name: 'Ice Cream', icon: FaIceCream },
  { id: '53', name: 'Fridge', icon: MdKitchen },
  { id: '54', name: 'Cutlery', icon: FaUtensils },
  { id: '55', name: 'Egg', icon: FaEgg },
  { id: '56', name: 'Cookie', icon: FaCookieBite },
  { id: '57', name: 'BBQ', icon: FaDrumstickBite },
  { id: '58', name: 'Chocolate', icon: FaCandyCane },
  { id: '59', name: 'Organic', icon: FaSeedling },
  { id: '60', name: 'Vegan', icon: FaCarrot },
  { id: '61', name: 'Outline Pizza', icon: PizzaSlice, isIconoir: true },
  { id: '62', name: 'Outline Coffee', icon: CoffeeCup, isIconoir: true },
  { id: '63', name: 'Outline Bread', icon: BreadSlice, isIconoir: true },
  { id: '64', name: 'Outline Ice Cream', icon: IceCream, isIconoir: true },
  { id: '65', name: 'Outline Fridge', icon: FridgeOutline, isIconoir: true },
  { id: '66', name: 'Outline Cutlery', icon: CutleryOutline, isIconoir: true },
  { id: '67', name: 'Outline Egg', icon: EggOutline, isIconoir: true },
  { id: '68', name: 'Outline Cookie', icon: CookieOutline, isIconoir: true },
  { id: '69', name: 'Outline BBQ', icon: BbqOutline, isIconoir: true },
  { id: '70', name: 'Outline Chocolate', icon: ChocolateOutline, isIconoir: true },
  { id: '71', name: 'Outline Organic', icon: OrganicFood, isIconoir: true },
  { id: '72', name: 'Outline Vegan', icon: VeganOutline, isIconoir: true }
];
